### ISSUE TITLE
Running ciab on apple silicone (M1 Macs)

### ISSUE THREAD

**Issue by dborinsk** [memsql/deployment-docker#4]
After spending some time trying to understand why ciab is not working on my Mac I figured out that Singlestoe cannot run on ARM arch.
For development and test flow there must be a solution or a workaround to solve it.
We want to keep our test flow isolated by using temporary containers dedicated for the tests and we dont want to use a real DB and manage the state just for the tests.
Will be great to understand if there is any way to run ciab on M1 macs, any other suggestions that do not require maintaining a cluster for tests or any ETA if there is one for this issue.

**Comment by arno756** [comment]
Hello, we have a good news.

With our 7.8.11 release, you can now run SingleStoreDB on M1 Macs. Provide feedback on this thread if you encounter any issue.

Make sure to pull the latest version when installing it:

```
docker run -i --init \
    --name singlestore-ciab \
    -e LICENSE_KEY=<YOUR_LICENSE_FROM_PORTAL.SINGLESTORE.COM> \
    -e ROOT_PASSWORD=<YOUR_DESIRED_DATABASE_ROOT_PASSWORD> \
    -p 3306:3306 -p 8080:8080 \
    singlestore/cluster-in-a-box:latest
```

**Comment by carlsverre** [comment]
Will close this issue unless someone re-opens with additional problems.

**Comment by JackEllis** [comment]
![image](https://i.gifer.com/origin/e3/e3c775e70d0e0d2250c6c900237b9125.gif)

**Comment by mark-b-ab** [comment]
I tried to start an instance and received error

`Latest errors from the database's tracelog:
02273679 2022-08-23 08:15:03.758   FAIL: Thread 115121: InitializeRepl: Failed to initialize replication subsystem because 'io_setup' system call failed with error 38 (Function not implemented).
: Failed to connect to the database: process exited: exit status 255`

**Comment by dborinsk** [comment]
Has someone been able to use the new docker image on M1 using testcontainers?

**Comment by carlsverre** [comment]
Not sure what you mean by testcontainers - but the new image does work on M1 in docker and rancher.

**Comment by dborinsk** [comment]
@carlsverre https://github.com/testcontainers/testcontainers-java
it works indeed on M1 but using this framework we still encounter same issue maybe its not related but wanted to know if someone was able to run it through testcontainers

**Comment by carlsverre** [comment]
@dborinsk can you switch over to our new image which you can find here along with specific docs for running in Docker on Apple Silicon (m1/m2 chips): https://github.com/singlestore-labs/singlestoredb-dev-image#how-to-run-the-docker-image-on-apple-silicon-m1m2-chips

Please give that a try first. If you are still having issues with that image and testcontainers please open an issue here: https://github.com/singlestore-labs/singlestoredb-dev-image/issues/new/choose

Thanks!

**Comment by dborinsk** [comment]
Thanks! I was missing the specific docker instructions. it works as a charm!
I created a gist with an example of a generic container for SingleStore using testcontainers if it might help anyone.
https://gist.github.com/dborinsk/f3977c5d834e0543fbb3538141e8e4e4

**Comment by carlsverre** [comment]
Glad it worked! And appreciate the testcontainers example, I'll add it to the docs for singlestoredb-dev-image.
